apiVersion: v1
kind: Pod
metadata:
  name: pgsql01
  labels:
    name: pgsql01
spec:
  containers:
    - image: launcher.gcr.io/google/postgresql9
      name: postgres
      env:
        - name: "POSTGRES_PASSWORD"
          value: "potato"
